# -*- coding: utf-8 -*-

player_stats_dic = {"level": 0,
                    "strength": 0,
                    "intellligence": 0,
                    "dexterity": 0,
                    "vitality": 0,
                    "critical_hit_chance": 0,
                    "critical_hit_danage": 0,
                    "dodge_chance": 0,
                    "armor": 0,
                    "physical_resistance": 0,
                    "cold_resistance": 0,
                    "fire_resistance": 0,
                    "lightning_resistance": 0,
                    "poison_resistance": 0,
                    "arcan_holy_resistance": 0,
                    "Life": 0,
                    "total_life_bonus": 0,
                    "life_per_hit": 0,
                    "life_per_kill": 0,
                    "resource_cost_reduction": 0,
                    "gold_find": 0,
                    "magic_find": 0,
                    "bonus_experience": 0}